agroal/agroal

agroal-pool/src/main/java/io/agroal/pool/ConnectionPool.java

https://issues.jboss.org/browse/AG-114

AG-114 - Improve exceptions for failed connection attempts

---

agroal-pool/src/main/java/io/agroal/pool/util/StampedCopyOnWriteArrayList.java

In the case a race condition is lost, i.e. `writeStamp == 0`, a thread would loop forever and never be able to get a hold of the lock because the stamp would not be updated. 
In order to improve structure and clarity, changed the remove method logic to:
1. Search for the element to remove
2. Lock the array
3. Search again if the array has been changed
4. Copy all other elements to the new array
5. Unlock

AG-145 - Fix race condition in StampedCopyOnWriteArrayList

---

agroal-api/src/main/java/io/agroal/api/configuration/AgroalConnectionPoolConfiguration.java
agroal-api/src/main/java/io/agroal/api/configuration/supplier/AgroalConnectionPoolConfigurationSupplier.java
agroal-api/src/main/java/io/agroal/api/configuration/supplier/AgroalPropertiesReader.java
agroal-pool/src/main/java/io/agroal/pool/ConnectionPool.java
agroal-pool/src/main/java/io/agroal/pool/Poolless.java
agroal-test/src/test/java/io/agroal/test/basic/BasicTests.java

An alternative to #27 using a setting

AG-155 - Add setting for multiple getConnection() by the same Thread

---

agroal-api/src/main/java/io/agroal/api/configuration/supplier/AgroalConnectionPoolConfigurationSupplier.java

The reasoning for the changed is detailed on [AG-174](https://issues.redhat.com/browse/AG-174)

AG-174 - Change default implementation of connection cache

---

agroal-pool/src/main/java/io/agroal/pool/ConnectionPool.java
agroal-pool/src/main/java/io/agroal/pool/util/PriorityScheduledExecutor.java
agroal-test/src/test/java/io/agroal/test/basic/NewConnectionTests.java

Changes to `PriorityScheduledExecutor` are probably overkill, but adding them anyway for future proofing.

AG-176 - Add warning on CreateConnectionTask

---

agroal-pool/src/main/java/io/agroal/pool/Poolless.java

Decrementing activeCount if getting an exception on createConnection

Fixed AG-194

---

agroal-pool/src/main/java/io/agroal/pool/ConnectionPool.java
agroal-test/src/test/java/io/agroal/test/basic/ResizeTests.java
agroal-test/src/test/java/io/agroal/test/basic/TimeoutTests.java

This  reworks `handlerFromSharedCache()` to simplify it a bit.

AG-201 - Attempt to use existing connections when new ones can't be established

---

agroal-spring-boot-starter/src/main/java/io/agroal/springframework/boot/metrics/AgroalDataSourcePoolMetadata.java
agroal-spring-boot-starter/src/main/java/io/agroal/springframework/boot/metrics/AgroalPoolDataSourceMetadataProviderConfiguration.java
agroal-spring-boot-starter/src/main/resources/META-INF/spring.factories
agroal-spring-boot-starter/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports

@barreiro : Would be nice to have it for a 2.2 and 1.18 version
Does include fix from #67

AG-205: Add DataSourcePoolMetadataProvider implementation

---

agroal-spring-boot-starter/src/main/java/io/agroal/springframework/boot/AgroalDataSource.java

@barreiro : Would be nice to have it for a 2.2 and 1.18 version

AG-207: Make ConnectionValidator and ExceptionSorter configurable

---

agroal-spring-boot-starter/src/main/java/io/agroal/springframework/boot/AgroalDataSource.java

Allow set jdbc properties and isolation level

AG-199 - Add setter for jdbcTransactionIsolation and jdbcProperties

---

agroal-spring-boot-starter/src/main/java/io/agroal/springframework/boot/metrics/AgroalDataSourcePoolMetricsAutoConfiguration.java
agroal-spring-boot-starter/src/main/java/io/agroal/springframework/boot/metrics/AgroalPoolDataSourceMetadataProviderConfiguration.java
agroal-spring-boot-starter/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports

@barreiro : Small fix to avoid `java.lang.ClassNotFoundException: io.micrometer.core.instrument.binder.MeterBinder`

AG-213: Small bugfix to micrometer implementation

---

agroal-narayana/src/main/java/io/agroal/narayana/NarayanaTransactionIntegration.java

Throw SQLException if enlistResource returns false

---

agroal-narayana/src/main/java/io/agroal/narayana/BaseXAResource.java

@barreiro : Fix for the wrong exception message I suggested on initial PR

AG-225 Fix wrong exception message

---

agroal-api/src/main/java/io/agroal/api/configuration/supplier/AgroalPropertiesReader.java
agroal-spring-boot-starter/src/main/java/io/agroal/springframework/boot/AgroalDataSource.java
agroal-spring-boot-starter/src/main/java/io/agroal/springframework/boot/metrics/AgroalDataSourcePoolMetricsAutoConfiguration.java

small improvement on property resolution. @graben can you give a quick review?

AG-210 - improve spring boot property resolution

---

.github/workflows/maven-action.yml

@barreiro : Just a small update for workflow actions

Update github actions to latest major versions

---

agroal-api/src/main/java/io/agroal/api/configuration/AgroalConnectionPoolConfiguration.java
agroal-api/src/main/java/io/agroal/api/configuration/supplier/AgroalConnectionPoolConfigurationSupplier.java
agroal-pool/src/main/java/io/agroal/pool/ConnectionPool.java
agroal-pool/src/main/java/io/agroal/pool/Poolless.java
agroal-spring-boot-starter/src/main/java/io/agroal/springframework/boot/AgroalDataSource.java
agroal-test/src/test/java/io/agroal/test/basic/BasicTests.java

@barreiro : A first idea how to implement a borrow validation feature

AG-229 - Add validate on borrow feature

---

agroal-narayana/src/main/java/io/agroal/narayana/RecoveryXAResource.java
agroal-test/src/test/java/io/agroal/test/narayana/RecoveryTests.java

@mmusgrov this addresses some of the points discussed in the issue

Delay opening of recovery connection

---

agroal-test/src/test/java/io/agroal/test/narayana/TransactionRecoveryTests.java
pom.xml

@barreiro: If you like to upgrade Narayana to 7.0.2 before next release, this will be needed.

Adjust TransactionRecoveryTests to new Narayana recovery mechanism

---

agroal-spring-boot-starter/src/main/java/io/agroal/springframework/boot/AgroalDataSource.java
agroal-spring-boot-starter/src/main/java/io/agroal/springframework/boot/AgroalDataSourceAutoConfiguration.java
agroal-test/src/test/java/io/agroal/test/springframework/AgroalDataSourceConfigurationTests.java

AG-248 - Enable setting of security provider, credentials and recoveryCredentials

---

agroal-spring-boot-starter/src/main/java/io/agroal/springframework/boot/AgroalDataSourceAutoConfiguration.java
agroal-test/src/test/java/io/agroal/test/springframework/AgroalDataSourceConfigurationTests.java

AG-249 - Add jta property to enable/disable integration from DataSource instance into Narayana

---

agroal-spring-boot-starter/src/main/java/io/agroal/springframework/boot/AgroalDataSourceAutoConfiguration.java

@barreiro: Accidentally added empty line

AG-248 - Remove empty line

---

agroal-api/src/main/java/io/agroal/api/configuration/AgroalConnectionPoolConfiguration.java
agroal-api/src/main/java/io/agroal/api/configuration/supplier/AgroalConnectionPoolConfigurationSupplier.java
agroal-pool/src/main/java/io/agroal/pool/ConnectionPool.java
agroal-pool/src/main/java/io/agroal/pool/Poolless.java
agroal-spring-boot-starter/src/main/java/io/agroal/springframework/boot/AgroalDataSource.java
agroal-test/src/test/java/io/agroal/test/narayana/RecoveryTests.java
agroal-test/src/test/java/io/agroal/test/springframework/AgroalDataSourceConfigurationTests.java

Add an option to disable recovery for a connection pool (https://issues.redhat.com/browse/AG-253)

AG-253 Add an option to disable recovery for a connection pool

---

agroal-spring-boot-starter/src/main/java/io/agroal/springframework/boot/AgroalDataSource.java

@barreiro: Ready to merge. Thx Benjamin

AG-256 - Add transactionRequirement and multipleAcquisition to Spring Boot support

---

agroal-spring-boot-starter/src/main/java/io/agroal/springframework/boot/health/AgroalDataSourceHealthContributorAutoConfiguration.java
agroal-spring-boot-starter/src/main/java/io/agroal/springframework/boot/health/AgroalDataSourceHealthIndicator.java
agroal-spring-boot-starter/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
agroal-test/src/test/java/io/agroal/test/springframework/health/AgroalDataSourceHealthContributorAutoConfigurationTests.java

@barreiro:  Please have a look at it.

AG-257 - Add health check that use internal isHealthy method
